utility/binds/which-key: allow configurable category labels
NotAShelf/neovim-flake pull request #235
Opened 2024-02-25 17:01 UTC by FrothyMarrow

Continuing #234

2024-02-26 03:33 UTC, NotAShelf requested changes

2024-02-26 03:33 UTC, NotAShelf commented on modules/filetree/nvimtree/config.nix
> +  inherit (lib) mkIf mkMerge mkBinding nvim boolToString defaultAttributes;
make imports explicit

2024-02-26 03:33 UTC, NotAShelf commented on lib/stdlib-extended.nix
> +    defaultAttributes = attr: self.mapAttrs (name: value: self.mkDefault value) attr;
I'm not sure if I like `defaultAttributes` as the function name. It should hint towards either the fact that it's a label (e.g. defaultLabels) or the fact that it's a constructor function (e.g mkDefaultLabelAttr)

2024-02-26 04:05 UTC, NotAShelf approved these changes

2024-02-27 17:44 UTC, horriblename approved these changes
LGTM

2024-02-27 18:28 UTC, merged